-- Select all data from the table
SELECT * FROM ewaste_india_dataset;

-- Find total records in the dataset
SELECT COUNT(*) AS Total_Records
FROM ewaste_india_dataset;

-- Show all unique states
SELECT DISTINCT(State)
FROM ewaste_india_dataset;

-- Show all unique categories
SELECT DISTINCT(Category)
FROM ewaste_india_dataset;

-- Show all unique regions
SELECT DISTINCT(Region)
FROM ewaste_india_dataset;

-- Aggregation Queries

-- Total e-waste generated by each state
SELECT State,
SUM(E_Waste_Generated_Tonnes) AS Total_ewaste
FROM ewaste_india_dataset
GROUP BY State
ORDER BY State;

--  Total e-waste collected by each region
SELECT Region,
SUM(E_Waste_Generated_Tonnes)
FROM ewaste_india_dataset
GROUP BY Region
ORDER BY Region;

-- Average collection rate by year
SELECT Year,
AVG(E_Waste_Collected_Tonnes)
FROM ewaste_india_dataset
GROUP BY Year
ORDER BY Year;

--  Total recycled waste by category
SELECT Category,
SUM(Recycled_Tonnes)
FROM ewaste_india_dataset
GROUP BY Category
ORDER BY Category;

-- Total hazardous waste by region
SELECT Region,
SUM(Hazardous_Waste_Tonnes)
FROM ewaste_india_dataset
GROUP BY Region
ORDER BY Region;

-- Average recycling efficiency by state
SELECT State,
AVG(Recycling_Efficiency)
FROM ewaste_india_dataset
GROUP BY State
ORDER BY State;

-- Ranking & Top N

--  Top 5 states by e-waste generated
SELECT TOP 5
State,
SUM(E_Waste_Generated_Tonnes) AS Total_ewaste
FROM ewaste_india_dataset
GROUP BY State
ORDER BY Total_ewaste DESC;

-- Bottom 5 states by collection rate
SELECT TOP 5
State,
SUM(Collection_Rate) AS Total_Collection
FROM ewaste_india_dataset
GROUP BY State
ORDER BY Total_Collection ASC;

-- Top 3 most hazardous categories
SELECT TOP 3
Category,
SUM(Hazardous_Waste_Tonnes) AS Total_Hazardous_Waste
FROM ewaste_india_dataset
GROUP BY Category
ORDER BY Total_Hazardous_Waste DESC; 

-- Highest recycling efficiency by region
SELECT TOP 1
Region,
SUM(Recycling_Efficiency) AS Total_Efficiency
FROM ewaste_india_dataset
GROUP BY Region
ORDER BY Total_Efficiency DESC;

-- Year-wise Analysis

-- Year-over-year total e-waste generated
SELECT Year,
SUM(E_Waste_Generated_Tonnes) AS Total_Ewaste_Generated
FROM ewaste_india_dataset
GROUP BY Year
ORDER BY Total_Ewaste_Generated;

-- Which year had the highest collection rate
SELECT TOP 1
Year,
SUM(E_Waste_Collected_Tonnes) AS Total_Ewaste_Collected
FROM ewaste_india_dataset
GROUP BY Year
ORDER BY Total_Ewaste_Collected DESC;

-- Compare 2018 vs 2023 generation per state
SELECT 
    State,
    SUM(CASE 
            WHEN Year = 2018
            THEN (E_Waste_Generated_Tonnes)
            ELSE 0
        END) AS Generated_2018,

    SUM(CASE 
            WHEN Year = 2023
            THEN (E_Waste_Generated_Tonnes)
            ELSE 0
        END) AS Generated_2023

FROM ewaste_india_dataset
GROUP BY State
ORDER BY State;

-- Year with highest hazardous waste
SELECT TOP 1
Year, 
SUM(Hazardous_Waste_Tonnes) AS Hazardous_Waste
FROM ewaste_india_dataset
GROUP BY Year
ORDER BY Year Desc;

-- Filtering Queries

-- All records where collection rate is below 20%
SELECT State,
Year, Category,
Collection_Rate
FROM ewaste_india_dataset
WHERE Collection_Rate < 0.20
ORDER BY Collection_Rate ASC;

-- States where recycling efficiency is above 80%
SELECT State,
Year, Category,
Recycling_Efficiency
FROM ewaste_india_dataset
WHERE Recycling_Efficiency > 0.80
ORDER BY Recycling_Efficiency;

-- Records from South region only
SELECT *
FROM ewaste_india_dataset
WHERE Region = 'South';

--  E-waste generated by mobile phones category across all years

SELECT Year, SUM(E_Waste_Generated_Tonnes) AS Total_Generated
FROM ewaste_india_dataset
WHERE Category = 'Mobile Phones & Tablets'
GROUP BY Year
ORDER BY Year;

-- Advanced Queries

-- States where collected waste is less than 25% of generated waste

SELECT State, 
       SUM(E_Waste_Generated_Tonnes) AS Total_Generated,
       SUM(E_Waste_Collected_Tonnes) AS Total_Collected,
       (SUM(E_Waste_Collected_Tonnes) / SUM(E_Waste_Generated_Tonnes)) * 100 AS Collection_Pct
FROM ewaste_india_dataset
GROUP BY State
HAVING (SUM(E_Waste_Collected_Tonnes) / SUM(E_Waste_Generated_Tonnes)) * 100 < 25
ORDER BY Collection_Pct;


-- Category contributing most hazardous waste per region
WITH RankedCategories AS (
    SELECT Region, Category,
           SUM(Hazardous_Waste_Tonnes) AS Total_Hazardous,
           RANK() OVER (PARTITION BY Region ORDER BY SUM(Hazardous_Waste_Tonnes) DESC) AS Rnk
    FROM ewaste_india_dataset
    GROUP BY Region, Category
)
SELECT Region, Category, Total_Hazardous
FROM RankedCategories
WHERE Rnk = 1
ORDER BY Region;


-- Year with best improvement in collection rate
WITH YearlyRate AS (
    SELECT Year,
           AVG(Collection_Rate) AS Avg_Collection_Rate,
           LAG(AVG(Collection_Rate)) OVER (ORDER BY Year) AS Prev_Year_Rate
    FROM ewaste_india_dataset
    GROUP BY Year
)
SELECT TOP 1 Year,
       Avg_Collection_Rate,
       Prev_Year_Rate,
       (Avg_Collection_Rate - Prev_Year_Rate) AS Improvement
FROM YearlyRate
WHERE Prev_Year_Rate IS NOT NULL
ORDER BY Improvement DESC;


-- Rank states within each region by total e-waste generated
SELECT Region, State,
       SUM(E_Waste_Generated_Tonnes) AS Total_Generated,
       RANK() OVER (PARTITION BY Region ORDER BY SUM(E_Waste_Generated_Tonnes) DESC) AS Rank_In_Region
FROM ewaste_india_dataset
GROUP BY Region, State
ORDER BY Region, Rank_In_Region;


-- Running total of e-waste generated year by year
SELECT Year,
       SUM(E_Waste_Generated_Tonnes) AS Yearly_Generated,
       SUM(SUM(E_Waste_Generated_Tonnes)) OVER (ORDER BY Year) AS Running_Total
FROM ewaste_india_dataset
GROUP BY Year
ORDER BY Year;


--  Gap between generated and collected waste per state
SELECT State,
       SUM(E_Waste_Generated_Tonnes) AS Total_Generated,
       SUM(E_Waste_Collected_Tonnes) AS Total_Collected,
       SUM(E_Waste_Generated_Tonnes) - SUM(E_Waste_Collected_Tonnes) AS Gap_Tonnes,
       ROUND((SUM(E_Waste_Generated_Tonnes) - SUM(E_Waste_Collected_Tonnes)) 
       / SUM(E_Waste_Generated_Tonnes) * 100, 2) AS Gap_Pct
FROM ewaste_india_dataset
GROUP BY State
ORDER BY Gap_Tonnes DESC;

-- Percentage contribution of each category to total national e-waste
SELECT Category,
       SUM(E_Waste_Generated_Tonnes) AS Total_Generated,
       ROUND(SUM(E_Waste_Generated_Tonnes) / 
       SUM(SUM(E_Waste_Generated_Tonnes)) OVER () * 100, 2) AS National_Share_Pct
FROM ewaste_india_dataset
GROUP BY Category
ORDER BY National_Share_Pct DESC;